[goldmark]
  [goldmark.renderer]
    unsafe = true
    hardWraps = false
    xhtml = false

  [goldmark.extensions]
    typographer = false

[highlight]
  codeFences = true
  guessSyntax = true
  hl_Lines = "--"
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = false
  noClasses = false
  style = "monokai"
  tabWidth = 2

[tableOfContents]
  endLevel = 4
  ordered = false
  startLevel = 2
