baseurl = "https://zietlow.io/"
Title = "Zietlow"
author = "Chris Zietlow"
copyright = "Copyright © 2008–2026, Chris Zietlow"

disqusShortname = "zietlow"

[pagination]
disableAliases = false
pagerSize = 10
path = 'path'

[taxonomies]
category = "categories"
tag = "tags"

[params]
author = "Chris"
twitter = "@aczietlow"
largeTwitterCard = false # set to true if you want to show a large twitter card image. The default is a small twitter card image
introDescription = "Recovering Software Engineer, Philomath, Shitty Photographer, Technologist, believes the oxford comma isn't optional."

# Google analytics Id
# ga_analytics = "UA-90881724-1"

# Baidu analytics Id
# baidu_analytics = "XXXXXXXX"

# will be used on share >> twitter, facebook, linkedin
fallBackOgImage = "images/camera-stock.jpeg"

# enable math notation. Switch to `true` to enable mathjax in your site.
enableMathNotation = true

# directory(s) where your articles are located
# see config details here https://gohugo.io/functions/where/#mainsectionss
mainSections = ["posts", "listens", "reads"]

# TODO: Create logo.
# logo = "logos/logo.png"

# Label Non inline images on an article body
figurePositionShow = false # toggle on or off globally
# you can toggle this behaviour on or off on per page using the same variable inside your articles frontmatter
figurePositionLabel = "Figure" # the text before image number e.g Figure 1.0

# Set the collapsed mobile navigation to either appear from the left or the right
mobileNavigation = "left" # if you prefer right change to 'right'

# enforceLightMode = false
enforceDarkMode = true

# Title separator, default to |.
titleSeparator = "|"

# Enable or disable comment globally. Default to true.
# comment = false

# Maximum number of recent posts.
# numberOfRecentPosts = 8

# Maximum number of featured posts.
# numberOfFeaturedPosts = 8

# Date format. Checkout https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for details.
dateFormat = "2006, Jan 06" # Default to "Jan 2, 2006".

# The year when ths website was created
since = 2012
