[[main]]
name = "Blog"
url = "posts/"
weight = -108

[[main]]
  name = "Cheatsheets"
  url = "cheatsheets/"
  weight = -108

[[main]]
  name = "Projects"
  url = "projects/"
  weight = -105

[[main]]
  name = "Library"
  url = "library/"
  weight = -101
 
[[main]]
  name = "Books"
  url = "books/"
  weight = -100

[[main]]
  name = "About"
  url = "about/"
  weight = -100

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/aczietlow"
  [social.params]
    indieAuth = true
[[social]]
  name = "drupal"
  type = "social"
  weight = 2
  url = "https://www.drupal.org/u/aczietlow"
[[social]]
 name = "twitter"
 type = "social"
 weight = 3
 url = "https://twitter.com/aczietlow"
 [social.params]
   indieAuth = true
[[social]]
  name = "linkedin"
  type = "social"
  weight = 4
  url = "https://www.linkedin.com/in/chris-zietlow-85b35849"
[[social]]
  name = "rss"
  weight = 5
  url = "index.xml"

